name: cosmic_oracle
description: "A cosmic oracle app, helping you make very important decisions."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.0
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Magic8Icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/magic_8_ball.png
    - assets/stars.jpeg
    - assets/galaxy.jpg
